### ISSUE TITLE
Quitar GORM y agregar conexión directa a pure Go postgres driver

### ISSUE THREAD

**Issue by sebajax** [sebajax/go-vertical-slice-architecture#1]
Quitar GORM y agregar conexión directa a pure Go postgres driver.

Agregar esto en database y cambiar queries a query de SQL.

**Comment by gaby** [comment]
@sebajax https://pkg.go.dev/github.com/gofiber/storage/postgres/v2

**Comment by sebajax** [comment]
> @sebajax https://pkg.go.dev/github.com/gofiber/storage/postgres/v2

Ya lo habíamos realizado hace tiempo. Gorm no va con la arquitectura que usamos.

**Comment by sebajax** [comment]
> @sebajax https://pkg.go.dev/github.com/gofiber/storage/postgres/v2

@gaby We already developed this some time ago. We didn’t close the issue. Thanks anyway for the replay.
