### ISSUE TITLE
Upgrade to GoFiber v2.52.1

### ISSUE THREAD

**Issue by gaby** [sebajax/go-vertical-slice-architecture#24]
@sebajax The latest v2 release is a security release. See details here: https://github.com/gofiber/fiber/releases/tag/v2.52.1

**Comment by sebajax** [comment]
> @sebajax The latest v2 release is a security release. See details here: https://github.com/gofiber/fiber/releases/tag/v2.52.1

Perfect @gaby will update to that version. Thanks!!.

**Comment by gaby** [comment]
It could go in this section https://github.com/gofiber/awesome-fiber#-boilerplates

**Comment by sebajax** [comment]
> It could go in this section https://github.com/gofiber/awesome-fiber#-boilerplates

@gaby Perfect!! I will do that so we can add this to Fiber examples. This type of architecture will be huge in some time and I will love to contribute to this awesome framework. 

https://www.linkedin.com/posts/sebastianituartebonfrisco_golang-go-uber-activity-7166850316313825280-nOZM?utm_source=share&utm_medium=member_ios
